# Variable Definition Include file
CODE_HOME=$(CURDIR)
BIN=$(CODE_HOME)/bin
OBJECTS=$(CODE_HOME)/objects
SOURCES=$(CODE_HOME)/src
HEADERS=$(CODE_HOME)/src
GCC=/usr/bin/g++
DEBUG= -g
INCLUDES= -I $(CODE_HOME)/src
GCC_FLAGS= -std=c++11
