# Variable Definition Include file
CODE_HOME=$(CURDIR)
BIN=$(CODE_HOME)/bin
OBJECTS=$(CODE_HOME)/objects
SOURCES=$(CODE_HOME)/sources
HEADERS=$(CODE_HOME)/sources
GCC=/usr/bin/g++
DEBUG= -g
INCLUDES= -I $(CODE_HOME)/sources
GCC_FLAGS= -std=c++11
